### PR TITLE
vaccine card added

### PR DESCRIPTION
**Pull request by mahmud6390**
vaccine card added
show value in medical history screen
https://github.com/OpenSRP/opensrp-client-chw/issues/343

### CODE REVIEW

**Comment by rkodev** [comment]
Screenshot_1558439748
Wrong graphic for vaccine card entry

**Comment by rkodev** [comment]
Screenshot_1558440467
Missing in medical history page

**Comment by rkodev** [comment]
Screenshot_1558441352
Missing in the overdue page. Service has an overdue state

**Comment by mahmud6390** [comment]
Vaccine card like as a Birthcertificate(optional) it'll not display in upcoming services.
vaccine card image not ready yet so that using temp image

**Pull request merged**
